// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brxardqbzmxmtkepcvni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyeGFyZHFiem14bXRrZXBjdm5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDU0NzAsImV4cCI6MjA2MzU4MTQ3MH0.-Ucnsa4vxJ-XW9J5u5xIl8Dh-t2ImG3xegVm5NRJX3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);